from typing import Dict, Any, List
from app.config_rl import rl_config

class ActionEngine:
    def __init__(self):
        self.limits = rl_config.threshold_limits

    def decode_action(self, continuous_action_vector: List[float]) -> Dict[str, Any]:
        """
        Maps a continuous vector generated by the policy into concrete limits.
        Assume vector is [conf_adjust, exp_adjust] generated by e.g. a linear model or bounded network.
        """
        # For safety, clip the raw outputs to the limits
        raw_conf = continuous_action_vector[0] if len(continuous_action_vector) > 0 else 0.0
        raw_exp = continuous_action_vector[1] if len(continuous_action_vector) > 1 else 0.0
        
        conf_adj = max(self.limits.min_confidence_adjust, min(self.limits.max_confidence_adjust, raw_conf))
        exp_adj = max(self.limits.min_exposure_adjust, min(self.limits.max_exposure_adjust, raw_exp))
        
        return {
            "confidence_adjustment": conf_adj,
            "exposure_multiplier": 1.0 + exp_adj,
            "raw_action_vector": continuous_action_vector
        }
